### Topics
- Numpy Package
    - Intro
    - Numpy arrays
        - 1d
        - 2d
        - Multidimensional Arrays
    - Mathematical opertors on ndarrays
        - Braodcasting
    - Functions and subpackges in numpy
    - Vectorize functions
        

In [1]:
import svec
svec.CollegeName

'SVEC'

In [2]:
svec.greet()

Hello world


In [3]:
svec.add(2,3)

5

### Numpy 

In [4]:
import numpy
numpy.array([11,22,33,44])

array([11, 22, 33, 44])

In [5]:
import numpy as np
np.array((2,3,4,5))

array([2, 3, 4, 5])

In [6]:
np.__version__ # double underscore

'1.15.4'

In [7]:
import pandas as pd
pd.__version__

'0.23.4'

In [8]:
#np.arange(start,stop,step_size)-->similar to range()
a1 = np.arange(10,16,1)

In [9]:
a1

array([10, 11, 12, 13, 14, 15])

In [15]:
print(type(a1))
print(a1.ndim) # no of dimensions
print(a1.shape)# no.of rows and columns
print(a1.size) # no of elements
print(a1.dtype)
print(a1.itemsize)# byte size of item

<class 'numpy.ndarray'>
1
(6,)
6
int32
4


In [16]:
a2 = np.array([[1,2],[3,4]])
a2

array([[1, 2],
       [3, 4]])

In [17]:
print(type(a2))
print(a2.ndim) # no of dimensions
print(a2.shape)# no.of rows and columns
print(a2.size) # no of elements
print(a2.dtype)
print(a2.itemsize)# byte size of item

<class 'numpy.ndarray'>
2
(2, 2)
4
int32
4


In [18]:
#np.linspace(start,stop, no of values to generate)
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

### np.ones and zeros

In [20]:
print(np.ones(6))
print(np.ones(6, dtype = int))

[1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1]


In [24]:
print(np.ones([2,3], dtype = int))

[[1 1 1]
 [1 1 1]]


### Identity and Diagnol matrix

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.diag([7,4,5])

array([[7, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

#### np.full((shape),element)

In [30]:
np.full((5,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [31]:
a2 = np.linspace(10,20,5)
a3 = np.linspace(1,10,5)
print(a2)
print(a3)

[10.  12.5 15.  17.5 20. ]
[ 1.    3.25  5.5   7.75 10.  ]


In [33]:
print(a2 * a3)# element wise multiplication
print(a2 + a3)# element wise addition
print(a2 - a3)
print(a2 % a3)
print(a2 / a3)

[ 10.     40.625  82.5   135.625 200.   ]
[11.   15.75 20.5  25.25 30.  ]
[ 9.    9.25  9.5   9.75 10.  ]
[0.   2.75 4.   2.   0.  ]
[10.          3.84615385  2.72727273  2.25806452  2.        ]


In [34]:
np.add(a2,a3)

array([11.  , 15.75, 20.5 , 25.25, 30.  ])

In [36]:
print(a2)
a2 + 5

[10.  12.5 15.  17.5 20. ]


array([15. , 17.5, 20. , 22.5, 25. ])

In [44]:
a4 = np.arange(15).reshape(3,5)
a5 = np.arange(5)
print(a4.shape)
print(a5.shape)
print(a4)
print(a5)
print(a4 + a5)

(3, 5)
(5,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4]
[[ 0  2  4  6  8]
 [ 5  7  9 11 13]
 [10 12 14 16 18]]


### Statistical Functions


In [50]:
a6 = np.array([40,10,20,50,30])
print(np.mean(a6))
print(np.min(a6))
print(np.max(a6))
print(np.median(a6))
print(np.quantile(a6,0.5)) # q2 is same as median
print(np.quantile(a6,0.25)) # q1 
print(np.quantile(a6,0.75)) # q3

30.0
10
50
30.0
30.0
20.0
40.0


In [51]:
np.__version__

'1.15.4'

In [61]:
print(np.log(2))# with base e
np.log(np.exp(1))# log e base e

0.6931471805599453


1.0

In [62]:
np.log(0)

C:\Users\krish\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [67]:
print(np.log(a6))
print(np.log2(2))
print(np.log2(8))
print(np.log1p(0))
print(np.log1p(2))# np.log(2+1)
print(np.log1p(a6))

[3.68887945 2.30258509 2.99573227 3.91202301 3.40119738]
1.0
3.0
0.0
1.0986122886681098
[3.71357207 2.39789527 3.04452244 3.93182563 3.4339872 ]


In [69]:
import math 
print(math.log(2))
#print(math.log(a6)) Error: only size-1 arrays can 
#be converted to Python scalars

0.6931471805599453


TypeError: only size-1 arrays can be converted to Python scalars

In [75]:
print(a6)
print(a6[0])
print(a6[1:])
print(a6 > 20)
print(a6[a6 > 20])

[40 10 20 50 30]
40
[10 20 50 30]
[ True False False  True  True]
[40 50 30]


In [76]:
for i in a6:
    print(i)

40
10
20
50
30


In [80]:
a7 = np.arange(8).reshape(4,2)
print(a7,'\n')
for i in a7:
    print(i)
    break

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[0 1]


In [82]:
a8 = np.arange(8).reshape(2,2,2)
#print(a8,'\n')
for i in a8:
    print(i)
    break

[[0 1]
 [2 3]]


In [83]:
a8

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [89]:
np.random.randint(5,10,1)

array([5])

In [94]:
np.random.randint(5,100,(2,5))

array([[93, 66, 69,  5, 72],
       [45, 63, 11, 46, 26]])

### Pandas
- Series
- DataFrame
- Panel

In [95]:
import pandas as pd
pd.__version__

'0.23.4'

In [96]:
pd.Series([10,20,200])

0     10
1     20
2    200
dtype: int64

In [97]:
np.array([10,20,200])

array([ 10,  20, 200])

In [102]:
s1 = pd.Series([10,20,200],['one','two','three'])
print(s1[0])
print(s1['one'])

10
10


In [103]:
d = {'student':44,'student2':50}
d

{'student': 44, 'student2': 50}

In [105]:
s2 = pd.Series(d)
s2

student     44
student2    50
dtype: int64

In [107]:
print(s2.shape)
print(s2.dtype)
print(s2.index)

(2,)
int64
Index(['student', 'student2'], dtype='object')


In [108]:
d2 = {'Name':['Raj','Ravi','Ram'],
      'Marks':[50,70,80],
      'Rollno':[416,435,511]}
d2

{'Name': ['Raj', 'Ravi', 'Ram'],
 'Marks': [50, 70, 80],
 'Rollno': [416, 435, 511]}

In [109]:
pd.DataFrame(d2)

Name  Marks  Rollno
0   Raj     50     416
1  Ravi     70     435
2   Ram     80     511

In [111]:
pd.read_csv('data.csv',header = None)

0   1    2
0   Raj  45  420
1   Ram  70  421
2  Ravi  80  423

In [113]:
pd.read_csv('data.csv',header = None,
            names = ['Name','Marks','RollNum'])

Name  Marks  RollNum
0   Raj     45      420
1   Ram     70      421
2  Ravi     80      423

In [114]:
pd.read_csv('data.csv',header = None,
            names = ['Name','Marks','RollNum'])

Name  Marks  RollNum
0   Raj   45.0      420
1   Ram    NaN      421
2  Ravi   80.0      423

In [117]:
df = pd.read_csv('data.csv',header = None,
            names = ['Name','Marks','RollNum'])

In [118]:
df

Name  Marks  RollNum
0   Raj   45.0      420
1   Ram    NaN      421
2  Ravi   80.0      423

In [119]:
df.index = ['one','two','three']
df

Name  Marks  RollNum
one     Raj   45.0      420
two     Ram    NaN      421
three  Ravi   80.0      423

In [1]:
import numpy as np
import pandas as pd

In [2]:
path = 'https://raw.githubusercontent.com/sumathi16/ML_FDP_SVEC/master/student_marks.csv'
student_marks_df = pd.read_csv(path)

In [3]:
student_marks_df

Roll Number    Name  English  Maths  Science
0          423     Raj     45.0   89.0       92
1          545     Ram      NaN   78.0       90
2          377    Ravi     65.0    NaN       77
3          510  Lokesh     67.0   32.0       44
4          602    Roja     64.0   37.0       76

In [4]:
student_marks_df.head() # default top five rows

Roll Number    Name  English  Maths  Science
0          423     Raj     45.0   89.0       92
1          545     Ram      NaN   78.0       90
2          377    Ravi     65.0    NaN       77
3          510  Lokesh     67.0   32.0       44
4          602    Roja     64.0   37.0       76

In [5]:
student_marks_df.head(2) # to dispaly top two 

Roll Number Name  English  Maths  Science
0          423  Raj     45.0   89.0       92
1          545  Ram      NaN   78.0       90

In [6]:
student_marks_df.tail(2) 

Roll Number    Name  English  Maths  Science
3          510  Lokesh     67.0   32.0       44
4          602    Roja     64.0   37.0       76

In [10]:
student_marks_df.sample()

Roll Number Name  English  Maths  Science
0          423  Raj     45.0   89.0       92

In [11]:
student_marks_df.sample(2)

Roll Number Name  English  Maths  Science
1          545  Ram      NaN   78.0       90
0          423  Raj     45.0   89.0       92

In [12]:
student_marks_df.columns

Index(['Roll Number', 'Name', 'English', 'Maths', 'Science'], dtype='object')

In [13]:
student_marks_df.shape

(5, 5)

In [14]:
student_marks_df.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
student_marks_df['Name']
student_marks_df.Name 

0       Raj
1       Ram
2      Ravi
3    Lokesh
4      Roja
Name: Name, dtype: object

In [19]:
student_marks_df['Roll Number']

0    423
1    545
2    377
3    510
4    602
Name: Roll Number, dtype: int64

In [16]:
type(student_marks_df['Name'])

pandas.core.series.Series

In [20]:
# DatafRame with multiple columns
student_marks_df[['Roll Number','Science']]

Roll Number  Science
0          423       92
1          545       90
2          377       77
3          510       44
4          602       76

In [21]:
type(student_marks_df[['Roll Number','Science']])

pandas.core.frame.DataFrame

In [22]:
# Dataframe with single column
student_marks_df[['Name']] 

Name
0     Raj
1     Ram
2    Ravi
3  Lokesh
4    Roja

In [25]:
student_marks_df.Science

0    92
1    90
2    77
3    44
4    76
Name: Science, dtype: int64

In [24]:
student_marks_df.Science > 70

0     True
1     True
2     True
3    False
4     True
Name: Science, dtype: bool

In [26]:
student_marks_df[student_marks_df.Science > 70]

Roll Number  Name  English  Maths  Science
0          423   Raj     45.0   89.0       92
1          545   Ram      NaN   78.0       90
2          377  Ravi     65.0    NaN       77
4          602  Roja     64.0   37.0       76

In [28]:
student_marks_df['Maths']\
    [student_marks_df.Science > 70]

0    89.0
1    78.0
2     NaN
4    37.0
Name: Maths, dtype: float64

In [29]:
student_marks_df[['Maths','English']]\
    [student_marks_df.Science > 70]

Maths  English
0   89.0     45.0
1   78.0      NaN
2    NaN     65.0
4   37.0     64.0

In [31]:
mask = (student_marks_df.Science > 70) & \
        (student_marks_df.Maths > 70)

In [32]:
mask

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [33]:
student_marks_df[mask]

Roll Number Name  English  Maths  Science
0          423  Raj     45.0   89.0       92
1          545  Ram      NaN   78.0       90

In [34]:
mask1 = (student_marks_df.Science > 70) | \
        (student_marks_df.Maths > 70)
student_marks_df[mask1]

Roll Number  Name  English  Maths  Science
0          423   Raj     45.0   89.0       92
1          545   Ram      NaN   78.0       90
2          377  Ravi     65.0    NaN       77
4          602  Roja     64.0   37.0       76

In [36]:
student_marks_df.isna()

Roll Number   Name  English  Maths  Science
0        False  False    False  False    False
1        False  False     True  False    False
2        False  False    False   True    False
3        False  False    False  False    False
4        False  False    False  False    False

In [37]:
student_marks_df

Roll Number    Name  English  Maths  Science
0          423     Raj     45.0   89.0       92
1          545     Ram      NaN   78.0       90
2          377    Ravi     65.0    NaN       77
3          510  Lokesh     67.0   32.0       44
4          602    Roja     64.0   37.0       76

In [39]:
# Column wise mising value count
student_marks_df.isnull().sum()

Roll Number    0
Name           0
English        1
Maths          1
Science        0
dtype: int64

In [43]:
#Missing value count in the Datframe
student_marks_df.isnull().sum().sum()

2

In [45]:
student_marks_df.dtypes

Roll Number      int64
Name            object
English        float64
Maths          float64
Science          int64
dtype: object

In [46]:
student_marks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
Roll Number    5 non-null int64
Name           5 non-null object
English        4 non-null float64
Maths          4 non-null float64
Science        5 non-null int64
dtypes: float64(2), int64(2), object(1)
memory usage: 280.0+ bytes


In [48]:
print(student_marks_df['English'].min())
print(student_marks_df['English'].max())
print(student_marks_df['English'].median())
print(student_marks_df['English'].mean())

45.0
67.0
64.5
60.25


In [49]:
student_marks_df.describe()

Roll Number    English     Maths    Science
count     5.000000   4.000000   4.00000   5.000000
mean    491.400000  60.250000  59.00000  75.800000
std      91.127932  10.242884  28.71701  19.214578
min     377.000000  45.000000  32.00000  44.000000
25%     423.000000  59.250000  35.75000  76.000000
50%     510.000000  64.500000  57.50000  77.000000
75%     545.000000  65.500000  80.75000  90.000000
max     602.000000  67.000000  89.00000  92.000000

In [50]:
student_marks_df.describe(include=np.int64)

Roll Number    Science
count     5.000000   5.000000
mean    491.400000  75.800000
std      91.127932  19.214578
min     377.000000  44.000000
25%     423.000000  76.000000
50%     510.000000  77.000000
75%     545.000000  90.000000
max     602.000000  92.000000

In [51]:
student_marks_df.describe(include=object)

Name
count      5
unique     5
top     Ravi
freq       1

In [53]:
student_marks_df.describe(include='all')

Roll Number  Name    English     Maths    Science
count      5.000000     5   4.000000   4.00000   5.000000
unique          NaN     5        NaN       NaN        NaN
top             NaN  Ravi        NaN       NaN        NaN
freq            NaN     1        NaN       NaN        NaN
mean     491.400000   NaN  60.250000  59.00000  75.800000
std       91.127932   NaN  10.242884  28.71701  19.214578
min      377.000000   NaN  45.000000  32.00000  44.000000
25%      423.000000   NaN  59.250000  35.75000  76.000000
50%      510.000000   NaN  64.500000  57.50000  77.000000
75%      545.000000   NaN  65.500000  80.75000  90.000000
max      602.000000   NaN  67.000000  89.00000  92.000000

Slicing and Subsetting
- Position Based -iloc
- Label Based -loc

In [54]:
student_marks_df

Roll Number    Name  English  Maths  Science
0          423     Raj     45.0   89.0       92
1          545     Ram      NaN   78.0       90
2          377    Ravi     65.0    NaN       77
3          510  Lokesh     67.0   32.0       44
4          602    Roja     64.0   37.0       76

In [55]:
student_marks_df.iloc[0,3]

89.0

In [56]:
student_marks_df.iloc[0:3:2,]

Roll Number  Name  English  Maths  Science
0          423   Raj     45.0   89.0       92
2          377  Ravi     65.0    NaN       77

In [58]:
student_marks_df.iloc[0:3:2,3]

0    89.0
2     NaN
Name: Maths, dtype: float64

In [59]:
student_marks_df.iloc[0:3:2,1:4:2]

Name  Maths
0   Raj   89.0
2  Ravi    NaN

In [60]:
student_marks_df.iloc[0,:]

Roll Number    423
Name           Raj
English         45
Maths           89
Science         92
Name: 0, dtype: object

In [61]:
student_marks_df.iloc[0:1,:]

Roll Number Name  English  Maths  Science
0          423  Raj     45.0   89.0       92

In [64]:
new_df = student_marks_df.set_index('Name')
new_df

Roll Number  English  Maths  Science
Name                                        
Raj             423     45.0   89.0       92
Ram             545      NaN   78.0       90
Ravi            377     65.0    NaN       77
Lokesh          510     67.0   32.0       44
Roja            602     64.0   37.0       76

In [63]:
student_marks_df

Roll Number    Name  English  Maths  Science
0          423     Raj     45.0   89.0       92
1          545     Ram      NaN   78.0       90
2          377    Ravi     65.0    NaN       77
3          510  Lokesh     67.0   32.0       44
4          602    Roja     64.0   37.0       76

In [67]:
student_marks_df.loc[0:3,'Roll Number':'Maths']

Roll Number    Name  English  Maths
0          423     Raj     45.0   89.0
1          545     Ram      NaN   78.0
2          377    Ravi     65.0    NaN
3          510  Lokesh     67.0   32.0

In [65]:
new_df.index

Index(['Raj', 'Ram', 'Ravi', 'Lokesh', 'Roja'], dtype='object', name='Name')

In [66]:
new_df.columns

Index(['Roll Number', 'English', 'Maths', 'Science'], dtype='object')

In [71]:
new_df.loc['Raj':'Lokesh','Roll Number':'English']

Roll Number  English
Name                        
Raj             423     45.0
Ram             545      NaN
Ravi            377     65.0
Lokesh          510     67.0

In [72]:
new_df.loc['Lokesh','English']

67.0

Handling Mising Values
- Delete the rows where misisng values are there
- Delete the columns where misisng values are there
- Replace the missing values with mean or with a value

In [74]:
### Delete rows
#student_marks_df.dropna(inplace=True)
#student_marks_df = student_marks_df.dropna()
student_marks_df.dropna()

Roll Number    Name  English  Maths  Science
0          423     Raj     45.0   89.0       92
3          510  Lokesh     67.0   32.0       44
4          602    Roja     64.0   37.0       76

In [75]:
student_marks_df.dropna(axis=1)

Roll Number    Name  Science
0          423     Raj       92
1          545     Ram       90
2          377    Ravi       77
3          510  Lokesh       44
4          602    Roja       76

In [76]:
student_marks_df.fillna(0)

Roll Number    Name  English  Maths  Science
0          423     Raj     45.0   89.0       92
1          545     Ram      0.0   78.0       90
2          377    Ravi     65.0    0.0       77
3          510  Lokesh     67.0   32.0       44
4          602    Roja     64.0   37.0       76

In [77]:
m = student_marks_df['English'].mean()
student_marks_df['English'].fillna(m)

0    45.00
1    60.25
2    65.00
3    67.00
4    64.00
Name: English, dtype: float64

In [78]:
m1 = student_marks_df['Maths'].mean()
student_marks_df['Maths'].fillna(m)

0    89.00
1    78.00
2    60.25
3    32.00
4    37.00
Name: Maths, dtype: float64

In [80]:
student_marks_df.dtypes

Roll Number      int64
Name            object
English        float64
Maths          float64
Science          int64
dtype: object

In [81]:
student_marks_df.columns

Index(['Roll Number', 'Name', 'English', 'Maths', 'Science'], dtype='object')

In [83]:
cat_cols = (student_marks_df.dtypes ==object)
cat_cols

Roll Number    False
Name            True
English        False
Maths          False
Science        False
dtype: bool

In [84]:
student_marks_df.columns[cat_cols]

Index(['Name'], dtype='object')

In [85]:
num_cols_mask = (student_marks_df.dtypes !=object)
num_cols_mask

Roll Number     True
Name           False
English         True
Maths           True
Science         True
dtype: bool

In [88]:
num_cols = student_marks_df.columns[num_cols_mask]
num_cols

Index(['Roll Number', 'English', 'Maths', 'Science'], dtype='object')

In [89]:
cleaned_data = student_marks_df.copy()

In [90]:
for col in num_cols:
    m = cleaned_data[col].mean()
    cleaned_data[col] =cleaned_data[col].fillna(m)

In [91]:
cleaned_data

Roll Number    Name  English  Maths  Science
0          423     Raj    45.00   89.0       92
1          545     Ram    60.25   78.0       90
2          377    Ravi    65.00   59.0       77
3          510  Lokesh    67.00   32.0       44
4          602    Roja    64.00   37.0       76